### ISSUE TITLE
GIS Software

### ISSUE THREAD

**Issue by MartinLuethi** [awesome-cryosphere/cryosphere-links#27]
The term GIS software is here used to mean "glaciers and ice sheets".
Commonly it is used for "Geographical Information System" (like ArcGIS, QGIS etc.).
This is extremely unfortunate, especially since the title says "GIS software".

**Comment by jlandmann** [comment]
Thanks a lot for this comment, @MartinLuethi !
I was indeed aware of this when I created the list. The one and only intention why I still chose the abbreviation in the subsections is to save some length in the titles, hoping that once writing it out in the main section would solve the issue. However, obviously it doesn't. I will make a PR later on and write out all "GIS" titles in full length.

**Comment by MartinLuethi** [comment]
> I was indeed aware of this when I created the list. The one and only intention why I still chose the abbreviation in the subsections is to save some length in the titles, hoping that once writing it out in the main section would solve the issue. However, obviously it doesn't. I will make a PR later on and write out all "GIS" titles in full length.

Or, use ISG, which has not meaning in connection the topic at hand.

Cheers, Martin

**Comment by jlandmann** [comment]
Perfect, I'll do that then! Thanks a lot for the suggestion! :-)

**Comment by jlandmann** [comment]
Okay, I took the shortcut and made a quick commit to master. If you like it this way, feel free to close.
